from server.resources.auth import *
from server.resources.lecturers import *
from server.resources.notes import *
from server.resources.courses import *
from server.resources.terms import *
from server.resources.comments import *
from server.resources.admin import *
from server.resources.grade_distributions import *
from server.resources.events import *
